title: FisherSkyi
author: "Yu Letian"
description: CS @ NUS · Research Portfolio
# theme: jekyll-theme-cayman
baseurl: ""
url: "https://fisherskyi.github.io"
permalink: pretty
nav: 
  - title: Home
    url: /
  - title: Research
    url: /research/
  - title: Projects
    url: /projects/
  - title: Teaching
    url: /teaching/
  - title: Blog
    url: /blog/
